[relay]
resolver="127.0.0.1:53"
listen_socks="0.0.0.0:1080"
[gateway.shadowsocks]
kind = "socks5"
host = "127.0.0.1"
port = 1081
[dns]
listen="127.0.0.1:53"
[dns.server.dns2socks]
addr="127.0.0.1:54"
[dns.server.dnspod]
addr="119.29.29.29:53"
[dns.rule]
blacklist="dns2socks"
else="dnspod"
